version: '3'

services:
  mongodb-estudos:
      image: bitnami/mongodb:latest
      networks:
        - base_network
      ports: 
        - "27027:27017"
      volumes:
        - .:/mongodb/estudos
      environment:
        MONGODB_USERNAME: ${MONGODB_USERNAME}
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
        MONGODB_DATABASE: ${MONGODB_DATABASE}

networks:
  base_network:

volumes:
  mongodb_estudos_data: